# Generated by Django 3.2.8 on 2021-10-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_recognize_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognize',
            name='source',
            field=models.URLField(),
        ),
    ]
